[tool.poetry]
name = "retroasm"
version = "0.1.0"
description = "Library and tools to convert between assembly and machine code"
authors = ["Maarten ter Huurne <maarten@treewalker.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
