[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 88
case_sensitive = true
combine_as_imports = true
from_first = true

[tool.poetry]
name = "retroasm"
version = "0.1.0"
description = "Library and tools to convert between assembly and machine code"
authors = ["Maarten ter Huurne <maarten@treewalker.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.0"

[tool.poetry.dev-dependencies]
invoke = "^1.2"
pytest = "^7.0.0"
pylint = "^2.3"
mypy = ">=0.930"
lxml = "^4.3.5"
pre-commit = "^2.15.0"
pyupgrade = "^2.29.0"
vulture = "^2.3"
Sphinx = "^4.3.1"
sphinxcontrib-spelling = "^7.3.0"
hypothesis = "^6.32.1"
sphinx-click = "^3.0.2"

[tool.poetry.scripts]
retro = 'retroasm.cmdline:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
