[tool.isort]
case_sensitive = true
combine_as_imports = true
from_first = true
multi_line_output = 6

[tool.poetry]
name = "retroasm"
version = "0.1.0"
description = "Library and tools to convert between assembly and machine code"
authors = ["Maarten ter Huurne <maarten@treewalker.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
Markdown = "^3.1"
isort = {version = "^4.3",extras = ["pyproject"]}
invoke = "^1.2"
pytest = "^4.5"
pytest-pythonpath = "^0.7.3"
mypy = "^0.701.0"
lxml = "^4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
